import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
class aiitem_model{
  List title_list = [
    "上传食物自动生成菜单",
    "拍食物查热量",
    "名字打分",
    "起名（个人、商业）",
    "手机号后四位打分",
    "作业辅导",
    "老照片修复",
    "AI一键姓氏壁纸",
    "一键提取短视频文案",
    "中小学作业辅导",
    "古风养生视频",
    "钦天监每日黄历",
    "小红书爆款心理学图文",
    "心理学火柴人治愈短视频",
    "抖音视频文案提取改写",
    "新闻采集风格改写存飞书",
    "养生行业批量出图",
    "宠物行业批量出图",
    "清醒奶奶治愈图",
    "历史行业批量出图",
    "装修行业批量出图",
    "美妆行业批量出图",
    "金融行业批量出图",
    "美食行业批量出图",
    "旅行行业批量出图",
    "国学运势行业批量出图",
    "治愈类视频生成",
    "历史故事视频生成",
    "输入文案生成历史故事",
    "如果书籍会说话教程",
    "养生动态视频",
    "育儿视频生成",
    "热门视频问答生成",
    "书单爆款视频",
    "长文文章写作",
    "朋友圈文案系统",
    "公众号图文生成",
    "公众号链接图文改写",
    "公众号爆款图文并配图",
    "人设IP文案精灵",
    "品牌故事生成",
    "巴菲特价值引擎",
    "张琦商业智友",
    "马云梦想引"
  ];
  List describe_list = [
    "上传食物图或名称，智能识别并推荐菜单，轻松制定营养美味的一日三餐",
    "拍一张食物照片，立即识别种类，精准估算热量与营养成分",
    "输入姓名，分析五行、音律、寓意等多维度，给出权威综合评分",
    "输入性别或行业需求，AI智能取名，兼顾音义美与吉祥寓意",
    "输入手机号后四位，分析数字能量与寓意，评估吉凶与运势",
    "上传题目图片或文字，AI秒级解答，提供详细步骤与讲解",
    "上传模糊老照片，AI自动上色清晰修复焕然一新",
    "输入姓氏，生成专属风格姓氏壁纸，适配锁屏、头像、朋友圈封面",
    "粘贴短视频链接，AI识别音频并提取字幕与文案，方便剪辑与整理",
    "上传题目或拍照，AI解析解题过程，支持语文数学英语等多科辅导",
    "生成古风风格养生类短视频，适配B站、小红书等平台",
    "结合传统钦天监算法，智能推算黄历宜忌，助你趋吉避凶",
    "输入关键词或热点话题，生成心理学风格爆款图文内容",
    "用火柴人风格演绎心理疗愈内容，简洁有趣、传播力强",
    "提取抖音视频文案，AI自动改写提升文案质量与互动率",
    "采集新闻内容，智能改写为小红书/公众号风格并保存到飞书",
    "批量生成中医养生、穴位调理等图文，适合健康类运营者",
    "生成宠物相关爆款图文，支持萌宠头像、美食等方向",
    "治愈风格插画“奶奶语录”图生成，走心走红双赢",
    "根据历史事件生成图文，风格贴合自媒体历史号需求",
    "提供装修前后效果图批量生成方案，提升用户留存率",
    "智能输出美妆测评、教程等图文内容，图文并茂更吸睛",
    "金融干货图文生成，包括理财、基金、财商等方向",
    "美食做法图文批量生成，适配公众号/小红书平台",
    "一键生成旅行路线图文、攻略封面、游记图册",
    "输出国学、命理、风水、生肖运势类图文内容",
    "输入关键词自动生成温暖治愈类视频，适配短视频平台",
    "基于输入主题生成历史故事短视频，包括配音与画面",
    "只需输入核心文案，自动匹配历史故事画面并生成视频",
    "书籍拟人化视频脚本生成工具，适用于“如果书会说话”类账号",
    "基于养生文案生成动态视觉短视频，吸睛又实用",
    "上传育儿主题，自动生成抖音、小红书育儿短视频",
    "针对爆款问答形式，自动生成评论回复类短视频",
    "根据输入书单，自动生成高转化书评视频内容",
    "自媒体长文智能写作，支持提纲扩写、润色校对",
    "朋友圈文案生成，支持节日问候、生活美学、情感分享",
    "输入主题即可自动生成图文，支持封面图与摘要",
    "粘贴原文链接，AI自动重写并生成公众号格式图文",
    "分析爆款内容，生成配图与文案，助力公众号运营",
    "打造鲜明人设IP文案，适用于明星网红自媒体",
    "生成品牌背景故事与传播文案，助力企业IP打造",
    "围绕价值投资理念输出内容，适合财经类自媒体",
    "提供商业洞察与热点分析内容生成，适配知识号",
    "生成马云风格梦想/创业金句文案，适合情绪共鸣传播"
  ];
  List type_list = [
    "生成菜单",
    "查热量",
    "姓名打分",
    "起名",
    "手机号打分",
    "作业辅导",
    "照片修复",
    "姓氏壁纸",
    "提取文案",
    "作业辅导",
    "古风视频",
    "黄历推算",
    "心理图文",
    "心理短视频",
    "文案改写",
    "内容采集改写",
    "养生图文",
    "宠物图文",
    "治愈插画",
    "历史图文",
    "装修图文",
    "美妆图文",
    "金融图文",
    "美食图文",
    "旅行图文",
    "国学图文",
    "治愈视频",
    "历史视频",
    "历史文案转视频",
    "拟人书籍视频",
    "养生动态视频",
    "育儿视频",
    "问答短视频",
    "书评短视频",
    "长文写作",
    "朋友圈文案",
    "公众号图文生成",
    "公众号改写",
    "公众号爆款图文",
    "IP人设文案",
    "品牌文案",
    "财经内容生成",
    "商业智友",
    "梦想金句生成"
  ];
  List icon_list = [
    Icon(Icons.dining_outlined, color: Colors.lightGreen, size: 35),
    Icon(Icons.local_fire_department, color: Colors.redAccent, size: 35),
    Icon(Icons.edit_note, color: Colors.indigo, size: 35),
    Icon(CupertinoIcons.lightbulb, color: Colors.cyan, size: 35),
    Icon(Icons.star_half, color: Colors.orangeAccent, size: 35),
    Icon(Icons.question_answer, color: Colors.blue.shade600, size: 35),
    Icon(Icons.auto_fix_high, color: Colors.teal, size: 35),
    Icon(Icons.wallpaper, color: Colors.purpleAccent, size: 35),
    Icon(Icons.video_library, color: Colors.green.shade600, size: 35),
    Icon(Icons.school, color: Colors.blue, size: 35),
    Icon(Icons.spa, color: Colors.teal, size: 35),
    Icon(Icons.wb_sunny, color: Colors.orange, size: 35),
    Icon(Icons.psychology, color: Colors.pink, size: 35),
    Icon(Icons.accessibility_new, color: Colors.deepPurple, size: 35),
    Icon(Icons.edit_document, color: Colors.green, size: 35),
    Icon(Icons.cloud_download, color: Colors.grey, size: 35),
    Icon(Icons.healing, color: Colors.redAccent, size: 35),
    Icon(Icons.pets, color: Colors.brown, size: 35),
    Icon(Icons.elderly, color: Colors.purpleAccent, size: 35),
    Icon(Icons.auto_stories, color: Colors.blueGrey, size: 35),
    Icon(Icons.house_siding, color: Colors.orangeAccent, size: 35),
    Icon(Icons.brush, color: Colors.pinkAccent, size: 35),
    Icon(Icons.monetization_on, color: Colors.green, size: 35),
    Icon(Icons.restaurant, color: Colors.deepOrange, size: 35),
    Icon(Icons.flight_takeoff, color: Colors.lightBlue, size: 35),
    Icon(Icons.book, color: Colors.amber, size: 35),
    Icon(Icons.self_improvement, color: Colors.lightGreen, size: 35),
    Icon(Icons.history_edu, color: Colors.indigo, size: 35),
    Icon(Icons.article, color: Colors.blueGrey, size: 35),
    Icon(Icons.menu_book, color: Colors.deepOrangeAccent, size: 35),
    Icon(Icons.local_hospital, color: Colors.red, size: 35),
    Icon(Icons.child_friendly, color: Colors.lightGreen, size: 35),
    Icon(Icons.question_answer, color: Colors.cyan, size: 35),
    Icon(Icons.library_books, color: Colors.tealAccent, size: 35),
    Icon(Icons.text_fields, color: Colors.blueAccent, size: 35),
    Icon(Icons.chat, color: Colors.purple, size: 35),
    Icon(Icons.rss_feed, color: Colors.blueGrey, size: 35),
    Icon(Icons.link, color: Colors.cyanAccent, size: 35),
    Icon(Icons.explore, color: Colors.orangeAccent, size: 35),
    Icon(Icons.face_retouching_natural, color: Colors.deepPurpleAccent, size: 35),
    Icon(Icons.flag, color: Colors.deepOrange, size: 35),
    Icon(Icons.trending_up, color: Colors.greenAccent, size: 35),
    Icon(Icons.insights, color: Colors.indigoAccent, size: 35),
    Icon(Icons.lightbulb_outline, color: Colors.yellow.shade700, size: 35),
  ];
}